version: '3'
services:
## NODE1
  opensearch-node1:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node1
    restart: always
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 900M
    volumes:
      - opensearch-data1:/usr/share/opensearch/data #Volumen para persistir datos
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net
## NODE1
  opensearch-node2:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node2
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 900M
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
## DASHBOARD
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    restart: always
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 900M
    depends_on:
      - opensearch-node1
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - opensearch-net

##Logstash server
  logstash:
    build: .
    restart: always
    container_name: logstash
    user: root
    environment:
      LS_JAVA_OPTS: -Xms4G -Xmx4G
      LOGSTASH_INTERNAL_PASSWORD: password
      LOG_LEVEL: debug
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 900M
    depends_on:
      - opensearch-dashboards
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/test.log:/usr/share/logstash/ingert_data/test.log
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net: