version: '3.3'
services:
  mysql:
    image: httpd:2.4.57-bookworm
    container_name: apache2
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    networks:
      - red_docker
    volumes:
    - ./web-side:/usr/local//apache2/htdocs
    - ./config/httpd.conf:/usr/local//apache2/conf/httpd.conf

networks:
  red_docker:
    name: red_docker
    external: true

#cpus: 1.5
#mem_limit: 2048m